a = input('digite alguma coisa:\n>>')
print('')
print('vc só digitou espaços? ', a.isspace())
print('vc só digitou numeros? ', a.isnumeric())
print('vc só digitou alguma letra? ', a.isalpha())
print('vc digitou letras e numeros?', a.isalnum())
print('vc digitou em maiusculo? ', a.isupper())
print('vc digitou em minusculo? ', a.islower())
print('vc digitou em maiusculo e em minusculo? ', a.istitle())